import { PrismaClient } from '@prisma/client'
import bcrypt from 'bcryptjs'

const prisma = new PrismaClient()

// All database patterns (120 patterns, 112 active)
const DATABASE_PATTERNS = [
  {
    code: 'checkerboard',
    name: 'Checkerboard',
    altNames: ["Chess Board"],
    category: 'block',
    difficulty: 4,
    requiredCells: [0,2,4,6,8,10,12,14,16,18,20,22,24],
    description: 'Form a checkerboard pattern',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: null,
  },
  {
    code: 'large_block',
    name: 'Large Block',
    altNames: ["4x4 Block"],
    category: 'block',
    difficulty: 4,
    requiredCells: [5,6,7,8,10,11,12,13,15,16,17,18,20,21,22,23],
    description: 'Form a large 4x4 block as depicted',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'medium_block',
    name: 'Medium Block',
    altNames: ["3x3 Block"],
    category: 'block',
    difficulty: 3,
    requiredCells: [6,7,8,11,12,13,16,17,18],
    description: 'Form a medium 3x3 block in the center',
    isActive: false,
    canRotate: true,
    canMirror: false,
    animationDelay: 1400,
  },
  {
    code: 'postage_stamp',
    name: 'Postage Stamp',
    altNames: ["Stamp","Corner Block"],
    category: 'block',
    difficulty: 2,
    requiredCells: [0,1,5,6],
    description: 'Mark a 2x2 block in any corner',
    isActive: true,
    canRotate: true,
    canMirror: false,
    animationDelay: 1500,
    excludedRanges: ["N"],
  },
  {
    code: 'small_block',
    name: 'Small Block',
    altNames: ["2x2 Block","Small Square"],
    category: 'block',
    difficulty: 2,
    requiredCells: [6,7,11,12],
    description: 'Form a small 2x2 block anywhere on the card',
    isActive: false,
    canRotate: true,
    canMirror: false,
    animationDelay: 1400,
  },
  {
    code: 'crazy_l',
    name: 'Crazy L',
    altNames: ["Any L"],
    category: 'crazy',
    difficulty: 3,
    requiredCells: [0,5,10,15,20,21,22,23,24],
    description: 'Form an L in any orientation',
    isActive: true,
    canRotate: true,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'hardway_bingo',
    name: 'Hardway Bingo',
    altNames: ["No Free Space"],
    category: 'crazy',
    difficulty: 2,
    requiredCells: [15,16,17,18,19],
    description: 'Complete any line without using the FREE space',
    isActive: true,
    canRotate: true,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'christmas_tree',
    name: 'Christmas Tree',
    altNames: ["Tree","Xmas Tree"],
    category: 'holiday',
    difficulty: 4,
    requiredCells: [2,6,7,8,10,11,12,13,14,17,22],
    description: 'Form a Christmas tree shape',
    isActive: false,
    canRotate: false,
    canMirror: false,
    animationDelay: null,
  },
  {
    code: 'easter_egg',
    name: 'Easter Egg',
    altNames: ["Egg"],
    category: 'holiday',
    difficulty: 3,
    requiredCells: [2,6,7,8,10,11,12,13,14,16,17,18,22],
    description: 'Form an Easter egg shape',
    isActive: false,
    canRotate: false,
    canMirror: false,
    animationDelay: null,
  },
  {
    code: 'pumpkin',
    name: 'Pumpkin',
    altNames: ["Jack-o-lantern","Halloween"],
    category: 'holiday',
    difficulty: 4,
    requiredCells: [1,2,3,5,7,9,10,11,12,13,14,15,19,21,22,23],
    description: 'Form a jack-o\'-lantern outline with face holes for Halloween',
    isActive: false,
    canRotate: false,
    canMirror: false,
    animationDelay: null,
  },
  {
    code: 'letter_c',
    name: 'Letter C',
    altNames: ["C Pattern"],
    category: 'letter',
    difficulty: 4,
    requiredCells: [0,1,2,3,4,5,10,15,20,21,22,23,24],
    description: 'Form the letter C with top row, left column, and bottom row',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1800,
  },
  {
    code: 'letter_f',
    name: 'Letter F',
    altNames: ["f"],
    category: 'letter',
    difficulty: 1,
    requiredCells: [1,2,3,4,6,11,12,13,16,21],
    description: 'Form the lettter F, as depicted',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'letter_h',
    name: 'Letter H',
    altNames: ["H Pattern"],
    category: 'letter',
    difficulty: 4,
    requiredCells: [0,4,5,9,10,11,12,13,14,15,19,20,24],
    description: 'Form the letter H with left column, right column, and middle row (no N column)',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
    excludedRanges: ["N"],
  },
  {
    code: 'letter_k',
    name: 'Letter K',
    altNames: ["k"],
    category: 'letter',
    difficulty: 3,
    requiredCells: [1,4,6,8,11,12,16,18,21,24],
    description: 'Form the letter K, as depicted',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
    excludedRanges: ["N"],
  },
  {
    code: 'letter_l',
    name: 'Letter L',
    altNames: ["L Pattern"],
    category: 'letter',
    difficulty: 3,
    requiredCells: [0,5,10,15,20,21,22,23,24],
    description: 'Form the letter L with left column and bottom row',
    isActive: true,
    canRotate: false,
    canMirror: true,
    animationDelay: 1500,
  },
  {
    code: 'letter_n',
    name: 'Letter N',
    altNames: ["N Pattern"],
    category: 'letter',
    difficulty: 4,
    requiredCells: [0,4,5,6,9,10,12,14,15,18,19,20,24],
    description: 'Form the letter N with left column, right column, and diagonal',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
    excludedRanges: ["N"],
  },
  {
    code: 'letter_t',
    name: 'Letter T',
    altNames: ["T Pattern"],
    category: 'letter',
    difficulty: 3,
    requiredCells: [0,1,2,3,4,7,12,17,22],
    description: 'Form the letter T with top row and middle column',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1800,
  },
  {
    code: 'letter_u',
    name: 'Letter U',
    altNames: ["U Pattern"],
    category: 'letter',
    difficulty: 4,
    requiredCells: [0,4,5,9,10,14,15,19,20,21,22,23,24],
    description: 'Form the letter U with left and right columns plus bottom row',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: null,
  },
  {
    code: 'letter_x',
    name: 'Letter X',
    altNames: ["X Pattern"],
    category: 'letter',
    difficulty: 3,
    requiredCells: [0,4,6,8,12,16,18,20,24],
    description: 'Form the letter X by marking both diagonals',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
    excludedRanges: ["N"],
  },
  {
    code: 'letter_z',
    name: 'Letter Z',
    altNames: ["Z Pattern"],
    category: 'letter',
    difficulty: 4,
    requiredCells: [0,1,2,3,4,8,12,16,20,21,22,23,24],
    description: 'Form the letter Z with top row, diagonal, and bottom row',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1800,
  },
  {
    code: 'big_cross',
    name: 'Cross',
    altNames: ["Big Cross"],
    category: 'line',
    difficulty: 1,
    requiredCells: [2,5,6,7,8,9,12,17,22],
    description: 'Form a cross as depicted',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'double_bingo',
    name: 'Double Bingo',
    altNames: ["Two Lines No Free","Double Line Hard Way"],
    category: 'line',
    difficulty: 3,
    requiredCells: [0,1,2,3,4,15,16,17,18,19],
    description: 'Complete two lines (vertical or horizontal, or one of each) without using the free space',
    isActive: true,
    canRotate: true,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'diagonal',
    name: 'Many Diagonal',
    altNames: ["Diagonal Line"],
    category: 'line',
    difficulty: 5,
    requiredCells: [0,6,12,18,24],
    description: 'Complete either diagonal line on all 4 cards',
    isActive: true,
    canRotate: true,
    canMirror: false,
    animationDelay: 1500,
    excludedRanges: ["N"],
  },
  {
    code: 'single_line',
    name: 'Single Line',
    altNames: ["Straight Line","Line Bingo"],
    category: 'line',
    difficulty: 1,
    requiredCells: [10,11,12,13,14],
    description: 'Complete any single line horizontally, vertically, or diagonally',
    isActive: false,
    canRotate: false,
    canMirror: false,
    animationDelay: null,
  },
  {
    code: 'two_lines',
    name: 'Two Lines',
    altNames: ["Double Line","Double Bingo"],
    category: 'line',
    difficulty: 2,
    requiredCells: [5,6,7,8,9,15,16,17,18,19],
    description: 'Complete any two separate lines',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: null,
  },
  {
    code: 'airplane',
    name: 'Airplane',
    altNames: [],
    category: 'shape',
    difficulty: 4,
    requiredCells: [1,6,9,10,11,12,13,14,16,19,21],
    description: 'Form an airplane shape',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
    excludedRanges: ["N"],
  },
  {
    code: 'anchor',
    name: 'Anchor',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [1,2,3,7,12,15,17,19,20,21,22,23,24],
    description: 'Form the pattern, as depicted.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'any_8-pack',
    name: 'Any 8-Pack',
    altNames: [],
    category: 'shape',
    difficulty: 4,
    requiredCells: [6,7,11,12,16,17,21,22],
    description: 'Form a block of 8 spots, with two rows of 4 or two columns of 4, side by side to form a rectangle of 8 spots.',
    isActive: true,
    canRotate: true,
    canMirror: true,
    animationDelay: 1500,
  },
  {
    code: 'any_three_corners',
    name: 'Any Three Corners',
    altNames: [],
    category: 'shape',
    difficulty: 3,
    requiredCells: [3,4,8,9,15,16,18,19,20,21,23,24],
    description: 'Form the pattern, as depicted.',
    isActive: true,
    canRotate: true,
    canMirror: false,
    animationDelay: 1500,
    excludedRanges: ["N"],
  },
  {
    code: 'arrow',
    name: 'Arrow',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [0,1,2,5,6,10,12,18,24],
    description: 'Form the pattern, as depicted.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'arrow_down',
    name: 'Arrow Down',
    altNames: ["Down Arrow"],
    category: 'shape',
    difficulty: 3,
    requiredCells: [2,7,10,11,12,13,14,16,17,18,22],
    description: 'Form an arrow pointing downward',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'arrow_up',
    name: 'Arrow Up',
    altNames: ["Up Arrow"],
    category: 'shape',
    difficulty: 3,
    requiredCells: [2,6,7,8,10,11,12,13,14,17,22],
    description: 'Form an arrow pointing upward',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'arrowhead_any_way',
    name: 'Arrowhead Any Way',
    altNames: ["Arrowhead"],
    category: 'shape',
    difficulty: 1,
    requiredCells: [2,3,4,8,9,14],
    description: 'Form the arrowhead, in any corner',
    isActive: true,
    canRotate: true,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'axe',
    name: 'Axe',
    altNames: [],
    category: 'shape',
    difficulty: 1,
    requiredCells: [2,4,6,7,8,9,12,14,19,24],
    description: 'Create the indicated shape.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
    excludedRanges: ["B"],
  },
  {
    code: 'barbell',
    name: 'Barbell',
    altNames: ["Barbell"],
    category: 'shape',
    difficulty: 2,
    requiredCells: [5,9,10,11,12,13,14,15,19],
    description: 'Form the pattern, as depicted',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
    excludedRanges: ["N"],
  },
  {
    code: 'beer_mug',
    name: 'Beer Mug',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [0,1,2,3,4,5,7,9,10,12,14,15,17,20,21,22],
    description: 'Create the pattern, as depicted.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'bench',
    name: 'Bench',
    altNames: [],
    category: 'shape',
    difficulty: 1,
    requiredCells: [10,11,12,13,14,16,18,21,23],
    description: 'Create the indicated shape.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
    excludedRanges: ["N"],
  },
  {
    code: 'bingo_man',
    name: 'Bingo Man',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [2,5,6,7,8,9,12,16,18,20,24],
    description: 'Create the indicated shape.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'boat',
    name: 'Boat',
    altNames: ["boat"],
    category: 'shape',
    difficulty: 2,
    requiredCells: [2,6,7,12,15,16,17,18,19,21,22,23],
    description: 'Form a boat, as depicted ',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'brackets',
    name: 'Brackets',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [0,1,3,4,5,9,15,19,20,21,23,24],
    description: 'Form the designated shape',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
    excludedRanges: ["N"],
  },
  {
    code: 'butterfly',
    name: 'Butterfly',
    altNames: ["Wings"],
    category: 'shape',
    difficulty: 4,
    requiredCells: [0,4,5,6,8,9,10,12,14,15,16,18,19,20,24],
    description: 'Form a butterfly with wings on both sides',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
    excludedRanges: ["N"],
  },
  {
    code: 'cash',
    name: 'Cash',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [1,2,3,4,5,7,11,12,13,17,19,20,21,22,23],
    description: 'Create the pattern, as depicted.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'cent_sign',
    name: 'Cent Sign',
    altNames: ["cent"],
    category: 'shape',
    difficulty: 1,
    requiredCells: [2,6,7,8,11,16,17,18,22],
    description: 'Form a cent sign, as depicted',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
    excludedRanges: ["B","O"],
  },
  {
    code: 'checkmark',
    name: 'Checkmark',
    altNames: ["checkmark"],
    category: 'shape',
    difficulty: 1,
    requiredCells: [4,8,10,12,15,16,20],
    description: 'Create the pattern, as depicted',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
    excludedRanges: ["N"],
  },
  {
    code: 'cleat',
    name: 'Cleat',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [11,12,13,14,15,16,17,18,19,20,21,23,24],
    description: 'Create the pattern, as depicted.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'convertible',
    name: 'Convertible',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [7,11,15,16,17,18,19,21,23],
    description: 'Create the pattern, as depicted.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'crazy_arrow',
    name: 'Crazy Arrow',
    altNames: ["arrow"],
    category: 'shape',
    difficulty: 3,
    requiredCells: [2,6,7,8,10,11,12,13,14,17,22],
    description: 'Form an arrow in any direction',
    isActive: true,
    canRotate: true,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'crazy_bowtie',
    name: 'Crazy Bowtie',
    altNames: ["crazy bowtie"],
    category: 'shape',
    difficulty: 1,
    requiredCells: [3,4,8,9,12,15,16,20,21],
    description: 'Form a bowtie, diagonally, in either direction',
    isActive: true,
    canRotate: true,
    canMirror: false,
    animationDelay: 1500,
    excludedRanges: ["N"],
  },
  {
    code: 'crazy_bowtie_plus_two_corners',
    name: 'Crazy Bowtie + Two Corners',
    altNames: [],
    category: 'shape',
    difficulty: 4,
    requiredCells: [0,3,4,8,9,12,15,16,20,21,24],
    description: 'Create the pattern in either configuration.',
    isActive: true,
    canRotate: false,
    canMirror: true,
    animationDelay: 1500,
    excludedRanges: ["N"],
  },
  {
    code: 'cross_stitch',
    name: 'Cross Stitch',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [0,4,7,11,13,17,20,24],
    description: 'Form the designated shape',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'double_chevron',
    name: 'Double Chevron',
    altNames: [],
    category: 'shape',
    difficulty: 1,
    requiredCells: [2,6,8,10,12,14,16,18,20,24],
    description: 'Create the indicated shape.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'double_cross',
    name: 'Double Cross',
    altNames: ["doublecross"],
    category: 'shape',
    difficulty: 2,
    requiredCells: [6,8,10,11,12,13,14,16,18],
    description: 'Create the pattern, as depicted.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
    excludedRanges: ["N"],
  },
  {
    code: 'double_frame',
    name: 'Double Frame',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [0,1,2,5,7,10,11,12,13,14,17,19,22,23,24],
    description: 'Form the designated shape',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'double_l',
    name: 'Double L',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [0,1,5,6,10,11,15,16,17,18,19,20,21,22,23,24],
    description: 'Create the pattern, as depicted.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'double_x',
    name: 'Double X',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [0,2,6,10,12,14,18,22,24],
    description: 'Create the pattern, as depicted.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'field',
    name: 'Field',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [5,6,7,8,9,10,14,15,19,20,21,22,23,24],
    description: 'Create the pattern, as depicted.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'flag',
    name: 'Flag',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,20],
    description: 'Form the pattern, as depicted.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'football',
    name: 'Football',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [0,1,2,5,6,7,8,10,11,12,13,14,16,17,18,19,22,23,24],
    description: 'Create the pattern, as depicted.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'four_corners',
    name: 'Four Corners',
    altNames: ["Corners"],
    category: 'shape',
    difficulty: 1,
    requiredCells: [0,4,20,24],
    description: 'Mark all four corner squares',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
    excludedRanges: ["I","N","G"],
  },
  {
    code: 'full_diamond',
    name: 'Full Diamond',
    altNames: [],
    category: 'shape',
    difficulty: 3,
    requiredCells: [2,6,7,8,10,11,12,13,14,16,17,18,22],
    description: 'Form the pattern, as depicted.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'goalpost',
    name: 'Goalpost',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [0,4,5,9,10,11,12,13,14,17,22],
    description: 'Create the pattern, as depicted.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'hand_mirror',
    name: 'Hand Mirror',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [1,5,6,7,11,12,18,24],
    description: 'Create the pattern, as depicted.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'heart',
    name: 'Heart',
    altNames: ["Valentine Heart"],
    category: 'shape',
    difficulty: 4,
    requiredCells: [0,1,3,4,5,7,9,10,14,16,18,22],
    description: 'Form a heart shape',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'helmet',
    name: 'Helmet',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [1,2,3,5,6,7,8,9,12,13,14,15,16,17,18,19,21,22,23],
    description: 'Create the pattern, as depicted.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'high_heel',
    name: 'High Heel',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [4,8,9,12,13,14,15,16,17,19,20,21,22,24],
    description: 'Create the pattern, as depicted.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'hourglass',
    name: 'Hourglass',
    altNames: ["Bow Tie"],
    category: 'shape',
    difficulty: 4,
    requiredCells: [0,1,2,3,4,6,7,8,12,16,17,18,20,21,22,23,24],
    description: 'Form an hourglass with top row, bottom row, and both diagonals',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'jersey',
    name: 'Jersey',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [0,1,3,4,5,6,7,8,9,11,12,13,16,17,18,21,22,23],
    description: 'Create the pattern, as depicted.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'kite',
    name: 'Kite Any Top Corner',
    altNames: ["Kite Pattern"],
    category: 'shape',
    difficulty: 3,
    requiredCells: [3,4,8,9,12,16,20],
    description: 'Form a kite shape pointing upward in either top corner',
    isActive: true,
    canRotate: false,
    canMirror: true,
    animationDelay: 1500,
    excludedRanges: ["N"],
  },
  {
    code: 'large_diamond',
    name: 'Large Diamond',
    altNames: ["Big Diamond"],
    category: 'shape',
    difficulty: 3,
    requiredCells: [2,6,8,10,14,16,18,22],
    description: 'Form a large diamond shape covering most of the card',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'large_frame',
    name: 'Large Frame',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [0,1,2,3,4,5,9,10,14,15,19,20,21,22,23,24],
    description: 'Create the pattern, as depicted.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'large_kite',
    name: 'Large Kite',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [0,1,2,5,6,7,10,11,12,18,24],
    description: 'Form the pattern, as depicted, using either top corner.',
    isActive: true,
    canRotate: false,
    canMirror: true,
    animationDelay: 1500,
  },
  {
    code: 'large_rectangle',
    name: 'Large Rectangle',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [5,6,7,8,9,10,14,15,16,17,18,19],
    description: 'Form the shape, as depicted.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'layer_cake',
    name: 'Layer Cake',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [0,1,2,3,4,10,11,12,13,14,20,21,22,23,24],
    description: 'Create the pattern, as depicted.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'lipstick',
    name: 'Lipstick',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [2,7,11,12,13,16,17,18,21,22,23],
    description: 'Create the pattern, as depicted.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'love_letter',
    name: 'Love Letter',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [0,3,4,5,8,9,10,15,20,21,22,23,24],
    description: 'Create the pattern, as depicted.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'lucky_cent',
    name: 'Lucky Cent',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [2,6,7,8,11,16,17,18,22,24],
    description: 'Create the pattern, as depicted.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'lucky_seven',
    name: 'Lucky Seven',
    altNames: ["Number 7","Seven"],
    category: 'shape',
    difficulty: 3,
    requiredCells: [0,1,2,3,4,8,12,16,20],
    description: 'Form the number 7 pattern',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 2000,
  },
  {
    code: 'margarita',
    name: 'Margarita',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [0,4,6,7,8,12,17,21,22,23],
    description: 'Create the pattern, as depicted.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'necklace',
    name: 'Necklace',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [1,2,3,5,9,10,14,15,19,21,22,23],
    description: 'Create the pattern, as depicted.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'outside_square',
    name: 'Outside Square',
    altNames: ["Outer Square","Border"],
    category: 'shape',
    difficulty: 4,
    requiredCells: [0,1,2,3,4,5,9,10,14,15,19,20,21,22,23,24],
    description: 'Mark all squares around the outside edge',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: null,
  },
  {
    code: 'picnic_table',
    name: 'Picnic Table',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [0,1,2,3,4,6,8,12,16,18,20,24],
    description: 'Create the pattern, as depicted.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'plane',
    name: 'Plane',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [1,6,9,10,11,12,13,14,16,19,21],
    description: 'Form the pattern, as depicted.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
    excludedRanges: ["N"],
  },
  {
    code: 'large_cross',
    name: 'Plus Sign',
    altNames: ["Big Cross","Large Cross"],
    category: 'shape',
    difficulty: 3,
    requiredCells: [2,7,10,11,12,13,14,17,22],
    description: 'Form a large plus covering middle row and column',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'purse',
    name: 'Purse',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [1,2,3,5,9,10,11,12,13,14,15,19,20,21,22,23,24],
    description: 'Create the pattern, as depicted.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'pyramid',
    name: 'Pyramid',
    altNames: ["pyramid"],
    category: 'shape',
    difficulty: 2,
    requiredCells: [12,16,17,18,20,21,22,23,24],
    description: 'Create a pyramid, as depicted',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'quarterback',
    name: 'Quarterback',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [2,5,6,7,8,9,12,16,18,20,24],
    description: 'Create the pattern, as depicted.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'railroad_tracks',
    name: 'Railroad Tracks',
    altNames: ["Train Tracks","Parallel Lines"],
    category: 'shape',
    difficulty: 3,
    requiredCells: [0,4,5,9,10,14,15,19,20,24],
    description: 'Form parallel lines like railroad tracks',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
    excludedRanges: ["N","I","G"],
  },
  {
    code: 'inside_square',
    name: 'Round Robin',
    altNames: ["Inner Square","Hug","Picture Frame"],
    category: 'shape',
    difficulty: 3,
    requiredCells: [6,7,8,11,13,16,17,18],
    description: 'Form a square inside the card (excluding center)',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
    excludedRanges: ["B","O"],
  },
  {
    code: 'sailboat',
    name: 'Sailboat',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [2,7,8,12,15,16,17,18,19,21,22,23],
    description: 'Form the designated shape',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'scoreboard',
    name: 'Scoreboard',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [0,1,2,3,4,5,9,10,14,15,19,20,21,22,23,24],
    description: 'Create the pattern, as depicted.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'seven_on_top_bottom',
    name: 'Seven on Top and Bottom',
    altNames: [],
    category: 'shape',
    difficulty: 3,
    requiredCells: [0,2,3,21,22,23,24],
    description: 'Any seven spots on the first or last row.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'sexy_dress',
    name: 'Sexy Dress',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [1,3,6,7,8,16,17,18,20,21,22,23,24],
    description: 'Create the pattern, as depicted.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'shopping_cart',
    name: 'Shopping Cart',
    altNames: [],
    category: 'shape',
    difficulty: 1,
    requiredCells: [4,8,10,11,12,15,16,17,20,22],
    description: 'Create the indicated shape.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'six_around_the_corner',
    name: 'Six Around the Corner',
    altNames: [],
    category: 'shape',
    difficulty: 4,
    requiredCells: [0,1,2,3,4,5],
    description: 'Form a pattern of 5 in a row or column, with one in the next row or column, as depicted.',
    isActive: true,
    canRotate: true,
    canMirror: true,
    animationDelay: 1500,
  },
  {
    code: 'small_4_corners',
    name: 'Small 4 Corners',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [6,8,16,18],
    description: 'Form the shape, as depicted.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
    excludedRanges: ["B","N","O"],
  },
  {
    code: 'small_cross',
    name: 'Small Cross',
    altNames: ["Plus Sign","Small Plus"],
    category: 'shape',
    difficulty: 2,
    requiredCells: [2,7,11,12,13,17,22],
    description: 'Form a small cross through the center',
    isActive: false,
    canRotate: false,
    canMirror: false,
    animationDelay: null,
  },
  {
    code: 'small_diamond',
    name: 'Small Diamond',
    altNames: ["Diamond","Small Plus"],
    category: 'shape',
    difficulty: 2,
    requiredCells: [7,11,13,17],
    description: 'Form a small diamond shape around the center',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
    excludedRanges: ["B","O"],
  },
  {
    code: 'smiley_face',
    name: 'Smiley Face',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [6,8,15,19,21,22,23],
    description: 'Create the pattern, as depicted.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'spider',
    name: 'Spider',
    altNames: [],
    category: 'shape',
    difficulty: 3,
    requiredCells: [0,4,6,8,10,11,12,13,14,16,18,20,24],
    description: 'Form the designated shape',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
    excludedRanges: ["N"],
  },
  {
    code: 'spin_the_top',
    name: 'Spin The Top',
    altNames: [],
    category: 'shape',
    difficulty: 1,
    requiredCells: [1,2,3,7,10,11,12,13,14,16,17,18,22],
    description: 'Create the indicated shape.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'spray_perfume',
    name: 'Spray Perfume',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [0,6,8,10,12,13,16,18,20,23],
    description: 'Create the pattern, as depicted.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
    excludedRanges: ["N"],
  },
  {
    code: 'staircase',
    name: 'Staircase',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [4,8,9,12,13,14,16,17,18,19,20,21,22,23,24],
    description: 'Form the shape, as depicted.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'starburst',
    name: 'Starburst',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [0,4,6,8,11,12,13,16,18,20,24],
    description: 'Form the pattern, as depicted.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
    excludedRanges: ["N"],
  },
  {
    code: 'stop_sign',
    name: 'Stop Sign',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [1,2,3,5,9,10,14,15,19,21,22,23],
    description: 'Form the shape, as depicted.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'swatter_and_fly',
    name: 'Swatter and Fly',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [0,1,2,5,6,7,10,11,12,16,21,24],
    description: 'Form the designated shape',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'teeter_totter',
    name: 'Teeter Totter',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [0,6,12,17,18,22,24],
    description: 'Form the designated shape',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'telephone_pole',
    name: 'Telephone Pole',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [0,1,2,3,4,5,6,7,8,9,12,17,22],
    description: 'For the shape, as depicted.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'three_candles',
    name: 'Three Candles',
    altNames: [],
    category: 'shape',
    difficulty: 1,
    requiredCells: [2,5,9,12,15,17,19,20,22,24],
    description: 'Create the indicated shape.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'thunderbird',
    name: 'Thunderbird',
    altNames: ["thunderbird"],
    category: 'shape',
    difficulty: 3,
    requiredCells: [2,5,6,7,8,9,10,12,14,17,22],
    description: 'Create the pattern, as depicted',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'tic_tac_toe',
    name: 'Tic-Tac-Toe',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [0,2,4,10,12,14,20,22,24],
    description: 'Create the pattern, as depicted.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'top_hat',
    name: 'Top Hat',
    altNames: ["Hat Pattern"],
    category: 'shape',
    difficulty: 3,
    requiredCells: [6,7,8,11,12,13,16,17,18,20,21,22,23,24],
    description: 'Form a top hat shape',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'trophy',
    name: 'Trophy',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [1,3,5,6,8,9,11,12,13,17,21,22,23],
    description: 'Create the pattern, as depicted.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'umbrella',
    name: 'Umbrella',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [1,2,3,5,6,7,8,9,10,12,14,17,21,22],
    description: 'Form the shape, as depicted.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'whistle',
    name: 'Whistle',
    altNames: [],
    category: 'shape',
    difficulty: 2,
    requiredCells: [10,11,12,13,17,18,19,23],
    description: 'Create the pattern, as depicted.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'champagne_glass',
    name: 'Wine Glass',
    altNames: ["Wine Glass","Martini Glass"],
    category: 'shape',
    difficulty: 4,
    requiredCells: [0,1,2,3,4,6,8,12,17,21,22,23],
    description: 'Form the shape, as depicted.',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'x_with_postage_in_any_corner',
    name: 'X With Postage In Any Corner',
    altNames: [],
    category: 'shape',
    difficulty: 5,
    requiredCells: [0,3,4,6,8,9,12,16,18,20,24],
    description: 'Large X with a postage stamp in any corner.',
    isActive: true,
    canRotate: true,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'coverall',
    name: 'Coverall',
    altNames: ["Cover All Except Free","Almost Blackout"],
    category: 'special',
    difficulty: 5,
    requiredCells: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24],
    description: 'Mark all spaces on the bingo card except for the free space',
    isActive: true,
    canRotate: false,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'full_house',
    name: 'Full House',
    altNames: ["Blackout","Cover All","Full Card"],
    category: 'special',
    difficulty: 5,
    requiredCells: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24],
    description: 'Mark every square on the card',
    isActive: false,
    canRotate: false,
    canMirror: false,
    animationDelay: null,
  },
  {
    code: 'nine_pack',
    name: 'Nine Pack',
    altNames: ["9-Pack"],
    category: 'special',
    difficulty: 3,
    requiredCells: [0,1,2,5,6,7,10,11,12],
    description: '9 blocks in any corner',
    isActive: true,
    canRotate: true,
    canMirror: false,
    animationDelay: 1500,
  },
  {
    code: 'six_pack',
    name: 'Six Pack',
    altNames: ["6-Pack"],
    category: 'special',
    difficulty: 2,
    requiredCells: [0,1,2,5,6,7],
    description: 'Mark any 6 squares on the card in a 2x3 pattern',
    isActive: true,
    canRotate: true,
    canMirror: false,
    animationDelay: 1500,
  }
]
async function main() {
  console.log('Starting seed...')

  // Get credentials from environment variables with secure defaults
  const adminEmail = process.env.ADMIN_EMAIL || 'admin@bingo.local'
  const adminUsername = process.env.ADMIN_USERNAME || 'admin'
  const adminPassword = process.env.ADMIN_PASSWORD || 'admin123'

  const callerEmail = process.env.CALLER_EMAIL || 'caller@bingo.local'
  const callerUsername = process.env.CALLER_USERNAME || 'caller'
  const callerPassword = process.env.CALLER_PASSWORD || 'caller123'

  // Warn if using default passwords
  if (adminPassword === 'admin123') {
    console.warn('⚠️  WARNING: Using default admin password! Set ADMIN_PASSWORD in .env for security.')
  }
  if (callerPassword === 'caller123') {
    console.warn('⚠️  WARNING: Using default caller password! Set CALLER_PASSWORD in .env for security.')
  }

  // Create admin user
  const hashedPassword = await bcrypt.hash(adminPassword, 10)

  const adminUser = await prisma.user.upsert({
    where: { email: adminEmail },
    update: {},
    create: {
      email: adminEmail,
      username: adminUsername,
      password: hashedPassword,
      role: 'admin',
    },
  })

  console.log('✓ Created admin user:', adminUser.username)

  // Create caller user
  const callerUser = await prisma.user.upsert({
    where: { email: callerEmail },
    update: {},
    create: {
      email: callerEmail,
      username: callerUsername,
      password: await bcrypt.hash(callerPassword, 10),
      role: 'caller',
    },
  })

  console.log('✓ Created caller user:', callerUser.username)

  // Seed patterns with exact database content
  console.log('Seeding patterns...')
  let createdCount = 0
  let updatedCount = 0

  for (const pattern of DATABASE_PATTERNS) {
    const existingPattern = await prisma.pattern.findUnique({
      where: { code: pattern.code }
    })

    const result = await prisma.pattern.upsert({
      where: { code: pattern.code },
      update: {
        name: pattern.name,
        altNames: pattern.altNames,
        category: pattern.category,
        difficulty: pattern.difficulty,
        requiredCells: pattern.requiredCells,
        description: pattern.description,
        canRotate: pattern.canRotate,
        canMirror: pattern.canMirror || false,
        animationDelay: pattern.animationDelay,
        isActive: pattern.isActive
      },
      create: {
        code: pattern.code,
        name: pattern.name,
        altNames: pattern.altNames,
        category: pattern.category,
        difficulty: pattern.difficulty,
        requiredCells: pattern.requiredCells,
        description: pattern.description,
        canRotate: pattern.canRotate,
        canMirror: pattern.canMirror || false,
        animationDelay: pattern.animationDelay,
        isActive: pattern.isActive
      }
    })

    if (existingPattern) {
      updatedCount++
    } else {
      createdCount++
    }

    console.log(`${existingPattern ? 'Updated' : 'Created'} pattern: ${pattern.name} (${pattern.code}) - Active: ${pattern.isActive}`)
  }

  console.log(`✓ Patterns seeding complete: ${createdCount} created, ${updatedCount} updated (${DATABASE_PATTERNS.length} total)`)
  console.log(`  - Active patterns: ${DATABASE_PATTERNS.filter(p => p.isActive).length}`)
  console.log(`  - Inactive patterns: ${DATABASE_PATTERNS.filter(p => !p.isActive).length}`)

  // Create system settings
  await prisma.systemSettings.upsert({
    where: { key: 'app_name' },
    update: {},
    create: {
      key: 'app_name',
      value: 'Bingo Caller 3000',
    },
  })

  await prisma.systemSettings.upsert({
    where: { key: 'default_call_interval' },
    update: {},
    create: {
      key: 'default_call_interval',
      value: 10, // seconds
    },
  })

  console.log('\n✓ Database seeded successfully!')
  console.log('\n🎯 Next steps:')
  console.log('  1. Start the development server: npm run dev')
  console.log('  2. Visit http://localhost:3000')
  console.log(`  3. Login with username: ${adminUsername}, password: ${adminPassword === 'admin123' ? 'admin123 (CHANGE THIS!)' : '(as configured)'}`)
  console.log('\n⚠️  SECURITY: Remember to change default passwords before deploying to production!')
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })